### ISSUE TITLE
ReferenceError: Ember is not defined

### ISSUE THREAD

**Issue by michaelshobbs** [heroku/heroku-buildpack-emberjs#11]
getting the following error just in the last few hours in the herokuish test suite using this buildpack.

app repo: https://github.com/gliderlabs/herokuish/tree/master/buildpacks/buildpack-emberjs/tests/emberjs

```
/app/dist/fastboot/vendor-729826cb707ab39b486934806d61aab6.js:7
        'default': Ember
                   ^

ReferenceError: Ember is not defined
    at processEmberShims (/app/dist/fastboot/vendor-729826cb707ab39b486934806d61aab6.js:7:20)
    at /app/dist/fastboot/vendor-729826cb707ab39b486934806d61aab6.js:247:3
    at /app/dist/fastboot/vendor-729826cb707ab39b486934806d61aab6.js:251:3
    at Sandbox.VMSandbox.eval (/app/node_modules/fastboot/lib/vm-sandbox.js:14:14)
    at EmberApp.retrieveSandboxedApp (/app/node_modules/fastboot/lib/ember-app.js:134:13)
    at new EmberApp (/app/node_modules/fastboot/lib/ember-app.js:47:21)
    at FastBoot._buildEmberApp (/app/node_modules/fastboot/index.js:102:17)
    at new FastBoot (/app/node_modules/fastboot/index.js:47:10)
    at Worker.buildMiddleware (/app/node_modules/fastboot-app-server/lib/worker.js:53:21)
    at Worker.start (/app/node_modules/fastboot-app-server/lib/worker.js:27:30)
    at new FastBootAppServer (/app/node_modules/fastboot-app-server/lib/fastboot-app-server.js:33:19)
    at Object.<anonymous> (/app/node_modules/fastboot-cli/bin/ember-fastboot:36:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

If I remove `ember-cli-fastboot`, the app starts up and I think this is resolved. However, I'm not well versed in the ember ecosystem and am looking for a little guidance as to whether this is the appropriate fix and perhaps an explanation as to why or why not. Thanks!

**Comment by michaelshobbs** [comment]
Actually, removing `ember-cli-fastboot` changes the behavior of the app. (derp). Things seem to magically be working now...some unknown upstream dependency perhaps?

**Comment by rwjblue** [comment]
@michaelshobbs - Yes, there was a disturbance in the force.  It should be good now.

**Comment by michaelshobbs** [comment]
Any insight into said "disturbance?"

**Comment by rwjblue** [comment]
broccoli-caching-writer@2.3.0 broke the way the `vendor.js` file was concatenated. We reverted in 2.3.1 which killed the evil Sith that were attacking our applications.

**Comment by michaelshobbs** [comment]
refs: https://github.com/gliderlabs/herokuish/pull/163

**Comment by michaelshobbs** [comment]
@rwjblue Thank you for the explanation 😄
