### ISSUE TITLE
Cannot fetch static assets from API server via https with self-signed cert

### ISSUE THREAD

**Issue by drauschenbach** [heroku/heroku-buildpack-emberjs#27]
When a static API resource is attempted to be loaded from the API server, the following error occurs:

```
Error: unable to verify the first certificate
2017-03-14T17:05:43.590591491Z app[web.1]:     at Error (native)
2017-03-14T17:05:43.590658704Z app[web.1]:     at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
2017-03-14T17:05:43.590756506Z app[web.1]:     at emitNone (events.js:86:13)
2017-03-14T17:05:43.590775194Z app[web.1]:     at TLSSocket.emit (events.js:185:7)
2017-03-14T17:05:43.590840746Z app[web.1]:     at TLSSocket._finishInit (_tls_wrap.js:603:8)
2017-03-14T17:05:43.590858288Z app[web.1]:     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
```

Trying to set the NODE_TLS_REJECT_UNAUTHORIZED=0 env var has no effect.

**Comment by edmorley** [comment]
This buildpack has been deprecated (c06c1e31291c24f71e8d84225727887506c3c897), and it's also no longer possible for changes to be made to it, due to the issues mentioned in #61.
