### ISSUE TITLE
compatible with ember 2.16.2

### ISSUE THREAD

**Issue by dbinetti** [heroku/heroku-buildpack-emberjs#45]
Just tried to upgrade to ember 2.16.2 and got this:
```
Build failed.
The Broccoli Plugin: [SRIHashAssets] failed with:
Error: ENOENT: no such file or directory, open '/tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/tmp/uglify_writer-input_base_path-W21FznpS.tmp/assets/popper.js.map'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.readFileSync (fs.js:554:33)
    at UglifyWriter.processFile (/tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/broccoli-uglify-sourcemap/index.js:101:41)
    at /tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/broccoli-uglify-sourcemap/index.js:65:16
    at Array.forEach (<anonymous>)
    at /tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/broccoli-uglify-sourcemap/index.js:55:25
    at Array.forEach (<anonymous>)
    at UglifyWriter.build (/tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/broccoli-uglify-sourcemap/index.js:54:19)
    at /tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
The broccoli plugin was instantiated at: 
    at SRIHashAssets.Plugin (/tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at SRIHashAssets.CachingWriter [as constructor] (/tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/broccoli-caching-writer/index.js:18:10)
    at new SRIHashAssets (/tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/broccoli-sri-hash/index.js:32:17)
    at SRIHashAssets (/tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/broccoli-sri-hash/index.js:22:12)
    at Class.postprocessTree (/tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/ember-cli-sri/index.js:42:42)
    at projectOrAddon.addons.reduce (/tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (<anonymous>)
    at addonProcessTree (/tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/ember-cli/lib/broccoli/ember-app.js:661:12)
    at EmberApp.toTree (/tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/ember-cli/lib/broccoli/ember-app.js:1814:17)
    at module.exports (/tmp/build_64c2d36c35984ed0931aed84dError running: ember build --environment production 2>&1
2a20ec7/barberscore-barberscore-web-5514915/ember-cli-build.js:38:14)
    at Builder.setupBroccoliBuilder (/tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/ember-cli/lib/models/builder.js:30:10)
    at BuildTask.run (/tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at Promise.resolve.then (/tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/ember-cli/lib/models/command.js:243:46)
    at tryCatch (/tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/rsvp/dist/rsvp.js:538:13)
    at /tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/tmp/build_64c2d36c35984ed0931aed84d2a20ec7/barberscore-barberscore-web-5514915/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
-----> Failed trying to compile heroku/ember-cli-deploy
 !     Push rejected, failed to compile emberjs app.
 !     Push failed
```
Is it a build pack issue?

**Comment by dbinetti** [comment]
Answer:  no, no it is not.

https://github.com/kybishop/ember-popper/issues/46
